### ISSUE TITLE
Device check needed

### ISSUE THREAD

**Issue by Johannestegner** [jitesoft/webpage#12]
Mobile devices in portrait mode should probably use the `small` media ruleset even if they have a large resolution.

**Comment by Johannestegner** [comment]
Been looking at something like this:

```scss

@mixin landscape($size) {
  $break-small: 767px;
  $break-large: 1200px;

  @if ($size == small) {
    @media only screen and (max-width: $break-small) {
      @content;
    }
  }
  @else if ($size == medium) {
    @media only screen and (min-width: $break-small + 1) and (max-width: $break-large - 1) {
      @content;
    }
  }
  @else if ($size == large) {
    @media only screen and (min-width: $break-large) {
      @content;
    }
  }
}

@mixin portrait($size) {
  $break-small: 480px;
  $break-large: 1280px;

  @if ($size == small) {
    @media only screen and (orientation: portrait) and (max-width: $break-small) {
      @content;
    }
  } @else if ($size == medium) {
    @media only screen and (orientation: portrait) and (min-width: $break-small + 1) and (max-width: $break-large - 1) {
      @content;
    }
  } @else if ($size == large) {
    @media only screen and (orientation: portrait) and (min-width: $break-large) {
      @content;
    }
  }
}
```

Do any of you people with _real_ css/scss skills find this an okay set up to format for devices? :)
